#!/usr/bin/env perl
# 2014-04-14, Adam Bryt

use strict;
use warnings;

use File::Spec::Functions qw(catfile);
use File::Copy qw(copy);

my $BINDIR = glob( "~/bin" );
my $SCRIPT = "a2pdf";
my $MODE   = 0755;

if (! -d $BINDIR) {
    die "Destination directory '$BINDIR' don't exist\n";
}

my $dest = catfile($BINDIR, $SCRIPT);

printf "copy %s %s\n", $SCRIPT, $dest;
copy($SCRIPT, $dest)
    || die "Error in copy $SCRIPT to $BINDIR: $!\n";

printf "chmod %o %s\n", $MODE, $dest;
chmod($MODE, $dest)
    || die "Error in chmod $MODE $dest: $!\n";
