Skrypt a2pdf jest filtrem konwertującym tekst (plain text) do formatu
PDF. Potrafi konwertować tekst kodowany w UTF-8.

Do konwersji jest używany pdflatex -- tworzony jest tymczasowy
dokument LaTeXa z konwertowanym tekstem umieszczonym w środowisku
verbatim, dokument jest kompilowany przez pdflatex i zwracany jest
wynikowy PDF.

* Zależności

Skrypt używa następujących modułów perla:

: Cwd
: File::Basename
: File::Copy
: File::Slurp
: File::Temp
: Getopt::Long
: Try::Tiny
: YAML

Jeśli brakuje jakiegoś modułu to należy go zainstalować, np.
poleceniem:

: cpanm MODULE

Skrypt używa LaTeXa.

* Instalacja

Zainstalować zależności jeśli potrzeba.

Skopiować skrypt a2pdf do odpowiedniego katalogu bin. Można użyć
skryptu install, który instaluje a2pdf w katalogu ~/bin.

Jeśli trzeba zmienić domyślną konfigurację to należy skopiować plik
examples/a2pdf.conf do ~/.a2pdf.conf i zmienić go.

* Dokumentacja

Dokumentacja w postaci POD jest zawarta w skrypcie - można ją
wyświetlić poleceniem:

: perldoc a2pdf
